# Generated by Django 3.1.7 on 2021-05-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furnitori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emer', models.CharField(max_length=200)),
                ('adrese', models.CharField(max_length=200)),
                ('nipt', models.IntegerField()),
                ('nr_tel', models.IntegerField()),
                ('preferencial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Klienti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emer', models.CharField(max_length=200)),
                ('adrese', models.CharField(max_length=200)),
                ('nipt', models.IntegerField()),
                ('nr_tel', models.IntegerField()),
                ('preferencial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shitesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emer', models.CharField(max_length=200)),
                ('paga', models.IntegerField()),
            ],
        ),
    ]
