# Generated by Django 3.2 on 2021-05-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjekte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnitori',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='klienti',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shitesi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
