# Generated by Django 3.1.7 on 2021-05-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=200)),
                ('vit_prodhimi_f', models.IntegerField()),
                ('vit_prodhimi_m', models.IntegerField()),
                ('marka', models.CharField(max_length=200)),
                ('kategoria', models.CharField(max_length=200)),
                ('lenda_djegese', models.CharField(max_length=200)),
                ('cmim_b', models.IntegerField()),
                ('cmim_sh', models.IntegerField()),
                ('sasia', models.IntegerField()),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
