# Generated by Django 3.1.7 on 2021-05-06 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
        ('produkt', '0002_auto_20210506_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='kategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auto.kategoria'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='lenda_djegese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auto.lenda_djegese'),
        ),
    ]
